### ISSUE TITLE
Release 1.3.0 not found as Docker image

### ISSUE THREAD

**Issue by samip5** [tmatilai/ruuvi2mqtt#188]
According to recent commits, there should be a docker image for 1.3.0 but according to my Pi, there is not.

```
Unable to find image 'ghcr.io/tmatilai/ruuvi2mqtt:v1.3.0' locally
docker: Error response from daemon: manifest unknown.
```

**Comment by tmatilai** [comment]
Uh, the release workflow has indeed failed, but logs already expired. I'll take a look.

**Comment by tmatilai** [comment]
Not sure why the build fails for v1.3.0. The cargo lock file was not up-to-date, but not sure if that can be the reason.

Anyway, `v1.3.1` has been tagged and successfully built.

**Comment by tmatilai** [comment]
Note that the v1.3 container images _only_ include a built statically linked binary, built with MUSL instead of GNU libc. The size is much smaller, but there of course could be some incompatibilities.

Please report back especially if you find any issues.
