### ISSUE TITLE
Forgotten platform, arm64

### ISSUE THREAD

**Issue by samip5** [tmatilai/ruuvi2mqtt#34]
Please also build for arm64, aka Raspberry Pi 64-bit.

**Comment by tmatilai** [comment]
Thanks for the suggestion. I’m happy to add build for another architecture (assuming it goes smoothly). But it’ll take a few days that I’ll have time for this. Also need to handle the Dependabot updates.

**Comment by tmatilai** [comment]
@samip5 done!

As I don't have access to an arm64 Pi, I would appreciate if you could verify that the build works as expected.
 
Before I cut a new release, you can either use the container image `ghcr.io/tmatilai/ruuvi2mqtt:arm64` or download the `binaries` artifact [from here](https://github.com/tmatilai/ruuvi2mqtt/actions/runs/2402391120) (`aarch64-unknown-linux-gnu/ruuvi2mqtt` in the zip file).

**Comment by samip5** [comment]
I will let you know, currently waiting patiently for my own sensors as the ones i was using were not mine. :)

**Comment by samip5** [comment]
@tmatilai Verified to be working, but could you please change the way it generates the items in HA, so that all items are under one device so people can more easilly attach it to a room without needing to do all of these separately?

Example for Zigbee2MQTT sensor:
![image](https://user-images.githubusercontent.com/1703002/171642225-0cc3a249-3ebf-4978-b172-a6e8595b8cdb.png)

Current Ruuvi2mqtt sensor:
![image](https://user-images.githubusercontent.com/1703002/171642414-283b9347-aa61-410f-87c9-77f3e50beb32.png)
