### ISSUE TITLE
Better way to generate HA sensors

### ISSUE THREAD

**Issue by samip5** [tmatilai/ruuvi2mqtt#51]
Please change the way it generates the items in HA, so that all items are under one device so people can more easilly attach it to a room without needing to do all of these separately?

Example for Zigbee2MQTT sensor:
![image](https://user-images.githubusercontent.com/1703002/171642225-0cc3a249-3ebf-4978-b172-a6e8595b8cdb.png)

Current Ruuvi2mqtt sensor:
![image](https://user-images.githubusercontent.com/1703002/171642414-283b9347-aa61-410f-87c9-77f3e50beb32.png)

**Comment by tmatilai** [comment]
The behavior was mainly imitated from the zigbee2mqtt at the time, so not sure what’s the difference. Could you check how the mqtt discovery messages differ?

**Comment by samip5** [comment]
> The behavior was mainly imitated from the zigbee2mqtt at the time, so not sure what’s the difference. Could you check how the mqtt discovery messages differ? 

I'm not exactly sure how I would check those?

**Comment by tmatilai** [comment]
> I'm not exactly sure how I would check those?

Either with some mqtt client/browser, or from the source code. 🙂

But never mind, I’ll dig deeper when I’m able to prioritize some time for this project. This is fun, but unfortunately there are many things competing from the limited free time as always…

**Comment by tmatilai** [comment]
And note to mainly myself: check the HA docs if there are related (new?) features in the discovery protocol

**Comment by samip5** [comment]
Example payload of a zigbee2mqtt device under zigbee2mqtt tree:

```
{
  "battery": 100,
  "device": {
    "applicationVersion": 5,
    "dateCode": "20191205",
    "friendlyName": "Outdoor sensor",
    "hardwareVersion": 30,
    "ieeeAddr": "0x00158d0006c5eefb",
    "manufacturerID": 4151,
    "manufacturerName": "LUMI",
    "model": "WSDCGQ11LM",
    "networkAddress": 36016,
    "powerSource": "Battery",
    "softwareBuildID": "3000-0001",
    "stackVersion": 2,
    "type": "EndDevice",
    "zclVersion": 1
  },
  "humidity": 72.05,
  "last_seen": "2022-06-04T19:29:08.838Z",
  "last_seen": "2022-06-04T19:29:08.856Z",
  "linkquality": 99,
  "pressure": 1015.3,
  "pressure": 1015.5,
  "temperature": 12.78,
  "voltage": 3005
}
```

vs device in ruuvi2mqtt tree:
```
{
  "humidity": 38.7875,
  "pressure": 1008.29,
  "temperature": 22.885
  "humidity": 38.77,
  "pressure": 1008.28,
  "temperature": 22.905
}
```


Debug info for the zigbee2mqtt sensor attached. The ruuvi one's don't show up as a device at all, only as entities.


[mqtt-b66da4599b93a40ab42552e97855d769-Outdoor sensor-d39fa161ba21f17f4a35f44111a57a43.json.txt](https://github.com/tmatilai/ruuvi2mqtt/files/8838544/mqtt-b66da4599b93a40ab42552e97855d769-Outdoor.sensor-d39fa161ba21f17f4a35f44111a57a43.json.txt)
.

**Comment by tmatilai** [comment]
Thanks! That should help. 🙂 

[The docs](https://www.home-assistant.io/docs/mqtt/discovery/) indeed didn’t have any `device` block so I just went with minimal values. But (some day) I’ll dig deeper what is needed.

**Comment by tmatilai** [comment]
I guess this is relevant: https://www.home-assistant.io/integrations/sensor.mqtt/

**Comment by samip5** [comment]
I had to remove the tree from homeassistant/sensor/ruuvi_* and restart the ruuvi2mqtt before it got them tied together. Now it works like one would expect. Thank you. :)

P.S Terveisiä Oulusta. :+1:
